services:
  plc1:
    build: containers/hmi1
    container_name: HMI1
    stdin_open: true
    tty: true 
    privileged: true
    command: ["python3", "HMI1.py"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.11
  
  plc2:
    build: containers/hmi2
    container_name: HMI2
    stdin_open: true
    tty: true 
    privileged: true
    command: ["python3", "modbusClient.py", "192.168.0.11"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.21








networks:
  vlan1:
    driver: bridge
    name: ics_sim_net
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_ics_sim_net