services:
  hmi1:
    build: containers/hmi1
    container_name: HMI1
    command: ["python3", "HMI1.py", "192.168.0.21"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.11

  plc1:
    build: containers/plc1
    container_name: PLC1
    command: ["python3", "PLC1.py"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.21

  powermeter:
    build: containers/power-meter
    container_name: PowerMeter
    command: ["python3", "PowerMeter.py", "192.168.0.21"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.31

  transferswitch:
    build: containers/transfer-switch
    container_name: TransferSwitch
    command: ["python3", "TransferSwitch.py", "192.168.0.21"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.32


networks:
  vlan1:
    driver: bridge
    name: ics_sim_net
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_ics_sim_net