services:
  # Sensors + Actuators
  powermeter1:
    build: containers/powermeter1
    container_name: PowerMeter1
    privileged: true
    volumes:
      - "/dev/ttyS10:/dev/ttyS10"
    command: ["python3", "powermeter.py", "--comm", "/dev/ttyS10", "--webport", "3001"]
    ports:
      - "3001:3001"
    networks:
      vlan1:
        ipv4_address: 192.168.0.31

  transferswitch1:
    build: containers/transferswitch1
    container_name: TransferSwitch1
    privileged: true
    volumes:
      - "/dev/ttyS12:/dev/ttyS12"
    command: ["python3", "transferswitch.py", "--comm", "/dev/ttyS12", "--webport", "3002"]
    ports:
      - "3002:3002"
    networks:
      vlan1:
        ipv4_address: 192.168.0.32

  powermeter2:
    build: containers/powermeter2
    container_name: PowerMeter2
    privileged: true
    volumes:
      - "/dev/ttyS14:/dev/ttyS14"
    command: ["python3", "powermeter.py", "--comm", "/dev/ttyS14", "--webport", "3003"]
    ports:
      - "3003:3003"
    networks:
      vlan1:
        ipv4_address: 192.168.0.33

  transferswitch2:
    build: containers/transferswitch2
    container_name: TransferSwitch2
    privileged: true
    volumes:
      - "/dev/ttyS16:/dev/ttyS16"
    command: ["python3", "transferswitch.py", "--comm", "/dev/ttyS16", "--webport", "3004"]
    ports:
      - "3004:3004"
    networks:
      vlan1:
        ipv4_address: 192.168.0.34

  # PLCs
  plc1:
    build: containers/plc1
    container_name: PLC1
    privileged: true
    volumes:
      - "/dev/ttyS11:/dev/ttyS11"
      - "/dev/ttyS13:/dev/ttyS13"
    command: ["python3", "PLC.py", "--pmcomm", "/dev/ttyS11", "--tscomm",  "/dev/ttyS13"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.21
        
  plc2:
    build: containers/plc2
    container_name: PLC2
    privileged: true
    volumes:
      - "/dev/ttyS15:/dev/ttyS15"
      - "/dev/ttyS17:/dev/ttyS17"
    command: ["python3", "PLC.py", "--pmcomm", "/dev/ttyS15", "--tscomm", "/dev/ttyS17"]
    networks:
      vlan1:
        ipv4_address: 192.168.0.22

  # HMIs
  hmi:
    build: containers/hmi
    container_name: HMI
    command: ["python3", "HMI.py", "--plc1", "192.168.0.21", "--plc2", "192.168.0.22", "--webport", "1001"]
    ports:
      - "1001:1001"
    networks:
      vlan1:
        ipv4_address: 192.168.0.11

  # UIs
  powermeter1_ui:
    build: containers/powermeter1_ui
    container_name: PowerMeter1_UI
    command: ["serve", "-s", "build", "-l", "5000"]
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_ENDPOINT=http://192.168.0.31:3001/
    networks:
      vlan1:
        ipv4_address: 192.168.0.41



# Modbus TCP network
networks:
  vlan1:
    driver: bridge
    name: ics_sim_net
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_ics_sim_net